export const devices = [
  {
    id: 1,
    code: "PH1",
    description: "Philips TV",
    category: "TV",
    company: "Philips",
    resolution: "HD",
    diagonal: 46,
    width: 10,
    height: 15,
    weight: 2
  },
  {
    id: 2,
    code: "PH1",
    description: "Philips TV",
    category: "TV",
    company: "Philips",
    resolution: "Full HD",
    diagonal: 49,
    width: 10,
    height: 15,
    weight: 2
  },
  {
    id: 3,
    code: "SM1",
    description: "Samsung TV",
    category: "TV",
    company: "Samsung",
    resolution: "Full HD",
    diagonal: 50,
    width: 10,
    height: 15,
    weight: 2
  },
  {
    id: 4,
    code: "SM1",
    description: "Samsung TV",
    category: "TV",
    company: "Samsung",
    resolution: "4K",
    diagonal: 55,
    width: 10,
    height: 15,
    weight: 2
  },
  {
    id: 5,
    code: "AP1",
    description: "Iphone X",
    category: "phone",
    company: "Apple",
    resolution: "4K",
    diagonal: 5.8,
    width: 10,
    height: 15,
    weight: 2
  },
  {
    id: 6,
    code: "AP1",
    description: "Iphone 7S",
    category: "phone",
    company: "Apple",
    resolution: "Full HD",
    diagonal: 5.5,
    width: 10,
    height: 15,
    weight: 2
  },
  {
    id: 7,
    code: "AP2",
    description: "MacBook Pro",
    category: "laptop",
    company: "Apple",
    resolution: "8K",
    diagonal: 16,
    width: 10,
    height: 15,
    weight: 2
  },
  {
    id: 8,
    code: "SM2",
    description: "Samsung A30",
    category: "phone",
    company: "Samsung",
    resolution: "Full HD",
    diagonal: 6.4,
    width: 10,
    height: 15,
    weight: 2
  },
  {
    id: 9,
    code: "AP3",
    description: "iPad Pro",
    category: "tablet",
    company: "Apple",
    resolution: "4K",
    diagonal: 12.9,
    width: 10,
    height: 15,
    weight: 2
  },
  {
    id: 10,
    code: "SM3",
    description: "Samsung Galaxy Tab",
    category: "tablet",
    company: "Samsung",
    resolution: "Full HD",
    diagonal: 10.5,
    width: 10,
    height: 15,
    weight: 2
  }
];
